allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@pnpm/exe@11.28.5'
  - '@pnpm/linux-arm64@11.28.5'
  - '@pnpm/linux-x64@11.28.5'
  - '@pnpm/linuxstatic-x64@11.28.5'
  - '@pnpm/macos-arm64@11.28.5'
  - '@pnpm/win-arm64@11.28.5'
  - '@pnpm/win-x64@11.28.5'
